name: Build and Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ]
    runs-on: ubuntu-22.04
    name: Java ${{ matrix.Java }} Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Maven verify
        run: mvn -V -B verify
